name: HeadDrops
version: 2.0.1
author: pizzafreak08
main: de.timolia.headdrops.HeadDrops
website: http://www.timolia.de/
description: Make hostile Mobs and Players drop their Heads!
commands:
    head:
        description: Gives you or someone else the head of a specific Player
        usage: /head [player] <name of head>
    headdrops:
        description: Reload the plugin config
        usage: /headdrops <reload>
    myhead:
        description: Gives you your head
        usage: /myhead
    headinfo:
        description: Get the name of a clicked head displayed
        usage: /headinfo
    mobhead:
        description: Get the head from a specific mob
        usage: /mobhead <mob>